<Project>
  <PropertyGroup Label="Shared C# Build Settings" Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
	<IsAotCompatible>true</IsAotCompatible>
	<IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup Label="BitwardenApi Target Framework" Condition="'$(MSBuildProjectName)' == 'BitwardenApi'">
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Label="Windows App Target Framework" Condition="'$(MSBuildProjectName)' == 'FluentBitwarden.Ui' or '$(MSBuildProjectName)' == 'FluentBitwarden.AppHost' or '$(MSBuildProjectName)' == 'FluentBitwarden.Contracts'">
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
	<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
	<CsWin32RunAsBuildTask>true</CsWin32RunAsBuildTask>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
  </PropertyGroup>
</Project>
