<Project>
  <Import Project="$(MSBuildThisFileDirectory)FluentBitwarden.Windows.props" />

  <PropertyGroup Label="Windows Application Defaults">
    <OutputType>WinExe</OutputType>
    <SelfContained>false</SelfContained>
    <PublishSelfContained>false</PublishSelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishReadyToRunComposite>false</PublishReadyToRunComposite>
  </PropertyGroup>
</Project>
