<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\FluentBitwarden.Windows.props" />
  <Import Project="..\..\FluentBitwarden.Tests.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\src\FluentBitwarden.Contracts\FluentBitwarden.Contracts.csproj" />
    <ProjectReference Include="..\..\src\FluentBitwarden.Platform\FluentBitwarden.Platform.csproj" />
  </ItemGroup>

</Project>
