<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>FluentBitwarden.AppHost</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
    <CsWin32RunAsBuildTask>true</CsWin32RunAsBuildTask>
    <InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Dapper.AOT</InterceptorsPreviewNamespaces>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks> 
	<DisableRuntimeMarshalling>true</DisableRuntimeMarshalling>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\FluentBitwarden\Assets\Bitwarden_icon.ico" Link="Assets\Bitwarden_icon.ico" CopyToOutputDirectory="PreserveNewest" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BitwardenApi\BitwardenApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.HighPerformance" />
    <PackageReference Include="ConfigureAwait.Fody" PrivateAssets="all" ExcludeAssets="runtime">
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Dapper.AOT" />
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="MemoryPack" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.WindowsAppSDK.Foundation" />
    <PackageReference Include="Microsoft.WindowsAppSDK.Runtime" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>
</Project>
