<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BitwardenApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="ConfigureAwait.Fody" PrivateAssets="all" ExcludeAssets="runtime">
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MemoryPack" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Otp.NET" />
    <PackageReference Include="StronglyTypedId" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>

</Project>
