global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using FluentBitwarden.Contracts.Ipc.Abstractions;
global using FluentBitwarden.Platform.Ipc.Abstractions;
global using FluentBitwarden.Platform.Ipc.Internal;
global using MemoryPack;
global using Microsoft.Win32.SafeHandles;
global using Windows.Win32;
global using Windows.Win32.Foundation;
